WriteFile: Switch from t.Chmod to os.Chmod(t.Name(), ...)
google/renameio pull request #21
Opened 2020-09-06 21:24 UTC by andhe

The former errors on windows as there's no such syscall.

Fixes #17

2020-09-06 21:28 UTC, andhe commented
Test was tested with a trivial test program doing `if err := renameio.WriteFile("test.txt", []byte("foobar\n"), 0644); err != nil { ... }`. There was no error. The `test.txt` file was both successfully created when non-existant and successfully overwritten when existing.

2020-09-06 21:31 UTC, andhe commented
PS. I'm not signing anyones CLAs. There's absolutely no chance for such a trivial fix to be copyrightable anyway. If you can't accept trivial bugfixes like this without administrative hassle and bureaucracy you're contribution process is worse than even the FSF.

2020-09-06 21:50 UTC, twpayne commented
For info, with this change the tests still fail on Windows due to file permissions not matching their expected values. What's happening roughly is:
* Windows doesn't support UNIX-like file permissions.
* The Go standard library pretends that Windows supports UNIX-like file permissions by providing functions to manipulate them on Windows, except that really the Go standard library silently sets the permissions to something different to what you request (see the simple example in [this article](https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride) for exactly what Go does here).
* Consequently, on Windows calling `os.Stat` to check the permissions match what you just set with `os.Chmod` will always fail. This is exactly what [`TestWriteFile` does](https://github.com/google/renameio/blob/master/writefile_test.go#L50-L65), and this test fails with this patch.

Regarding the CLA, please note that I am a contributor to this project, not a maintainer and not associated with Google, so I cannot comment on that.

2020-09-06 22:24 UTC, andhe commented
Hi @twpayne 

I can sympathize with the thought of dropping support to avoid fooling anyone into thinking file replacement is actually atomic on Windows. However when pushing this up to the application authors, what's an application supposed to do about it that renameio can't? I bet the result will just be that applications goes back to homebrew code that's equally broken on all platforms, instead of just Windows. Maybe it's better to just document a big fat warning about Windows not being atomic at all in README. Also leaving the tests not passing on windows could be another warning.

2020-09-06 22:33 UTC, twpayne commented
Applications can call [`io/ioutil.WriteFile`](https://pkg.go.dev/io/ioutil?tab=doc#example-WriteFile) instead:

```go
func myAppWriteFile(filename string, data []byte, perm os.FileMode) error {
    switch runtime.GOOS {
    case "windows":
        return ioutil.WriteFile(filename, data, perm)
    default:
        return renameio.WriteFile(filename, data, perm)
    }
}
```

I agree that it's not obvious what the best way to handle this is. Another option would be for `renameio.WriteFile` to call `ioutil.WriteFile` on Windows, but that conceals the problem.

2020-09-06 23:40 UTC, matthiasng requested changes
Im not sure if this is a good solution but there sould be a dedicated section in the readme about windows support including:
- not atomic on windows 
- golang's strange chmod behaviour on windows

2020-09-07 06:28 UTC, stapelberg commented
This PR makes the code slightly less clean (specifying the file name instead of a file handle introduces the possibility for race conditions) only to work around the absence of a specific call, when the package doesn’t work correctly on windows anyway.

I’m inclined to merge https://github.com/google/renameio/pull/20 instead.

2020-09-10 10:17 UTC, closed without merging